global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  

scrape_configs:
  # - job_name: prometheus-internal
  #   static_configs:
  #     - targets: ["127.0.0.1:9090"]
  - job_name: devops
    metrics_path: /system/metrics
    static_configs:
      - targets: ["devops:9000"]