version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
      - type: bind
        source: ./elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms128M -Xmx128M
      - discovery.type=single-node
      - xpack.security.enabled=false
    hostname: es
    networks:
      - devops

  mariadb:
    image: mariadb:10.6.5-focal
    volumes:
      - type: bind
        source: ./mariadb
        target: /var/lib/mysql
    hostname: mariadb
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: Mar1aD@t@b@ยง3
    networks:
      - devops
    command: --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4

  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    networks:
      - devops

  devops:
    image: ghcr.io/yannick-xy/devops:latest
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - type: bind
        source: ./instance.conf
        target: /home/sirius/instance.conf
      - type: bind
        source: ./data
        target: /home/sirius/data
    networks:
      - devops

# MONITORING
# add Grafana/Graylog/whatever...

  prometheus:
    image: prom/prometheus:v2.36.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - devops

networks:
  devops: