name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: scireum/sirius-build-jdk18:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      # During workflow/job "build", functional tests are excluded because of
      # framework-related problems between Docker and sirius-kernel on GitHub.
      # Since the required framework for testing starts without any issues
      # locally, all tests are executable there.
      - name: Build devops project
        run: mvn clean package -Dtest.excluded.groups=local

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.KEY }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/yannick-xy/devops:latest
