name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: scireum/sirius-build-jdk18:4.1
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
        
      - name: Compile, test and build devops project
        run: mvn clean compile test package
     
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: devops
          password: ${{ secrets.KEY }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/devops:latest
