name: test
on:
  pull_request:

env:
  SIRIUS_DOCKER_HOST: ""

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: scireum/sirius-build-jdk18:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Check running docker-compose
        run: docker-compose up -f src/test/resources/docker-compose-test.yml

      - name: Compile and test devops project
        run: mvn clean compile test