name: test
on:
  pull_request:

env:
  SIRIUS_DOCKER_HOST: ""

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: scireum/sirius-build-jdk18:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      # During workflow/job "test", tests are run only without framework-start
      # because of problems between Docker, sirius-kernel and GitHub.
      # Locally, tests are running well since the framework starts
      # there without any issues.
      - name: Compile and test devops project
        run: mvn clean compile test -Dtest.excluded.groups=local
