name: test
on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: scireum/sirius-build-jdk18:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Compile and test devops project
        run: mvn clean compile test
