name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: scireum/sirius-build-jdk18:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Check running docker-compose
        run: docker-compose --version

      - name: Compile and test devops project
        run: mvn clean compile test