name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: scireum/sirius-build-jdk18:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Check running docker
        run: docker ps -a

      - name: Compile and test devops project
        run: mvn clean compile test